apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: wikimedia
  name: wikimedia-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wikimedia
        type: web
    spec:
      containers: []
